### ISSUE TITLE
Makefile still points to gym_micropolis directory

### ISSUE THREAD

**Issue by SBunce92** [smearle/gym-city#6]
This seems like a one-line fix to change to gym_city

**Comment by smearle** [comment]
Thanks, just pushed a fix for that now.

**Comment by SBunce92** [comment]
I was working on something myself - it seems it's a bit more complex than I first thought, as I'm still getting an error further down the line with swig:

`make[3]: Entering directory '/home/sam/Projects/gym-city/gym_city/envs/micropolis/MicropolisCore/src/TileEngine'
swig3.0 -python -py3 -c++ -Isrc -Wall \
        -outdir objs \
        -o objs/tileengine_wrap.cpp \
        swig/tileengine.i
Unable to open file objs/tileengine_wrap.cpp: No such file or directory
`

Hope this helps

**Comment by smearle** [comment]
Ah yes, I think you just need to manually make a directory called 'objs' in 'TileEngine.' We should probably just have the makefile do this automatically, maybe you can submit a pull request to that effect.

**Comment by SBunce92** [comment]
Also, partly my fault for capitalising 'makefile', but I think the change affects the lower case makefile instead. Happy to provide a PR for these changes if you like

**Comment by smearle** [comment]
Oops, I hadn't meant to include both makefiles in the repo; I was using 'makefile' for running demos (inference on trained agents), where the models are saved locally on my machine, but not in this repo (since they're large files). Ideally though, we could host those trained agents elsewhere and instruct the user to download them in the Readme, if they like.

**Comment by SBunce92** [comment]
I've been playing around with this for a few hours and seem to be digging myself deeper into a rabbit hole. I can submit a PR for the makefiles, which I have managed to mess about to get it to build correctly. However, I keep running into issues with gi, cairo, and swig is doing some odd things with imports. 

Given that there are many dependencies and conda doesn't seem to be able to resolve the requirements at present, it might be worth wrapping the project up in a Dockerfile at some point?

**Comment by smearle** [comment]
For sure, I'm curious what you've done with the makefiles. Yes, gi/cairo are usually the culprits, when trying to build. In the meantime, see if you can run the Game of Life environment, to make sure everything else is all good, something like:
`python3 main.py --env-name GameOfLifeEnv-v0 --experiment test --render` 
Are you using ubuntu? I haven't tried on Windows or OS X. In any case, post the error message(s) you're running into—I've gone through this process several times, and always get a little stuck. You're likely just missing some package or other relating to gi/cairo.

I definitely think it would be worthwhile to work on a Dockerfile, if only to sort out and record exactly which packages are required.

**Comment by smearle** [comment]
Hello again. I added a Dockerfile, which can train an agent with CUDA acceleration (and render the 0th environment). I still need to figure out how to save log files and models inside docker. You can also look at the Dockerfile to figure out what you will need to install in order to build locally (especially if you are using Ubuntu). Run `sh run.sh`, which will attempt to build and run the image specified by Dockerfile. It will take a while to build the image for the first time and still needs to be cleaned/optimized.
